services:
  # 1. PostgreSQL 16 (Databáza)
  postgres:
    image: postgres:16-alpine
    container_name: titan_db
    environment:
      POSTGRES_DB: titan_moonid
      POSTGRES_USER: titan_admin
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # 2. MinIO (S3 Compatible Storage pre obrázky/feedy)
  minio:
    image: minio/minio
    container_name: titan_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: titan_minio
      MINIO_ROOT_PASSWORD: minio_password_123
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI
    volumes:
      - ./minio-data:/data
